const OptionElementData = {
    tables: [
        'Table 1',
        'Table 2',
        'Table 3',
        'Table 4',
        'Table 5',
        'Table 6',
        'Table 7',
        'Table 8',
        'Table 9',
        'Table 10',
        'Table 11',
        'Table 12',
        'Table 13',
        'Table 14',
        'Table 15',
        'Bar Spot 1',
        'Bar Spot 2',
        'Bar Spot 3',
        'Bar Spot 4',
        'Bar Spot 5',
        'Bar Spot 6',
        'Bar Spot 7',
        'Bar Spot 8',
        'Bar Spot 9',
    ],
    hours: [
        '11:00',
        '12:00',
        '13:00',
        '14:00',
        '15:00',
        '16:00',
        '17:00',
        '18:00',
        '19:00',
        '20:00',
        '21:00',
        '22:00',
    ],
};

export default OptionElementData;
