const barChairsPosition = [
    {
        positionTop: '13%',
        positionLeft: '26.5%',
        rotation: null,
        numberRotation: null,
        numberPaddingRight: null,
        id: 'Bar Spot 1',
    },
    {
        positionTop: '20%',
        positionLeft: '26.5%',
        rotation: null,
        numberRotation: null,
        numberPaddingRight: null,
        id: 'Bar Spot 2',
    },
    {
        positionTop: '28.1%',
        positionLeft: '30%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 3',
    },
    {
        positionTop: '28.1%',
        positionLeft: '34.4%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 4',
    },
    {
        positionTop: '28.1%',
        positionLeft: '38.4%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 5',
    },
    {
        positionTop: '28.1%',
        positionLeft: '42.5%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 6',
    },
    {
        positionTop: '28.1%',
        positionLeft: '46.4%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 7',
    },
    {
        positionTop: '28.1%',
        positionLeft: '50.6%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 8',
    },
    {
        positionTop: '28.1%',
        positionLeft: '55%',
        rotation: '270deg',
        numberRotation: '90deg',
        numberPaddingRight: null,
        id: 'Bar Spot 9',
    },
];

export default barChairsPosition;
