import { createSlice } from '@reduxjs/toolkit';

const tablesSlice = createSlice({
    name: 'tables',
    initialState: {
        tables: [
            {
                id: 'Table 1',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '4',
                zone: 'Saloon',
                positionTop: '40%',
                positionLeft: '25%',
                tableNumber: 'Table 1',
                tableType: 'fourPeopleSaloon',
            },
            {
                id: 'Table 2',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '4',
                zone: 'Saloon',
                positionTop: '40%',
                positionLeft: '37%',
                tableNumber: 'Table 2',
                tableType: 'fourPeopleSaloon',
            },
            {
                id: 'Table 3',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '4',
                zone: 'Saloon',
                positionTop: '40%',
                positionLeft: '49%',
                tableNumber: 'Table 3',
                tableType: 'fourPeopleSaloon',
            },
            {
                id: 'Table 4',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '4',
                zone: 'Saloon',
                positionTop: '60%',
                positionLeft: '31%',
                tableNumber: 'Table 4',
                tableType: 'fourPeopleSaloon',
            },
            {
                id: 'Table 5',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '4',
                zone: 'Saloon',
                positionTop: '60%',
                positionLeft: '43%',
                tableNumber: 'Table 5',
                tableType: 'fourPeopleSaloon',
            },
            {
                id: 'Table 6',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '2',
                zone: 'Saloon',
                positionBottom: '5%',
                positionRight: '70%',
                tableNumber: 'Table 6',
                tableType: 'twoPeople',
            },
            {
                id: 'Table 7',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '2',
                zone: 'Saloon',
                positionBottom: '5%',
                positionRight: '32%',
                tableNumber: 'Table 7',
                tableType: 'twoPeople',
            },
            {
                id: 'Table 8',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '2',
                zone: 'Saloon',
                positionBottom: '25%',
                positionRight: '32%',
                tableNumber: 'Table 8',
                tableType: 'twoPeople',
            },
            {
                id: 'Table 9',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '8',
                zone: 'Saloon',
                tableType: 'eightPeople',
            },
            {
                id: 'Table 10',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '7',
                zone: 'Saloon',
                positionTop: '10%',
                positionRight: '30%',
                tableNumber: 'Table 10',
                rotation: null,
                tableType: 'sevenPeople',
            },
            {
                id: 'Table 11',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Smokers',
                countOfPeople: '7',
                zone: 'Terrace',
                positionTop: '3%',
                positionRight: '12%',
                tableNumber: 'Table 11',
                rotation: '270deg',
                tableType: 'sevenPeople',
            },
            {
                id: 'Table 12',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Smokers',
                countOfPeople: '4',
                zone: 'Terrace',
                positionTop: '35%',
                positionRight: '8%',
                tableNumber: 'Table 12',
                tableType: 'fourPeopleTerrace',
            },
            {
                id: 'Table 13',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Smokers',
                countOfPeople: '4',
                zone: 'Terrace',
                positionTop: '35%',
                positionRight: '19%',
                tableNumber: 'Table 13',
                tableType: 'fourPeopleTerrace',
            },
            {
                id: 'Table 14',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Smokers',
                countOfPeople: '4',
                zone: 'Terrace',
                positionTop: '70%',
                positionRight: '8%',
                tableNumber: 'Table 14',
                tableType: 'fourPeopleTerrace',
            },
            {
                id: 'Table 15',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Smokers',
                countOfPeople: '4',
                zone: 'Terrace',
                positionTop: '70%',
                positionRight: '19%',
                tableNumber: 'Table 15',
                tableType: 'fourPeopleTerrace',
            },
        ],
        barSpots: [
            {
                id: 'Bar Spot 1',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '13%',
                positionLeft: '26.5%',
                rotation: null,
                numberRotation: null,
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 2',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '20%',
                positionLeft: '26.5%',
                rotation: null,
                numberRotation: null,
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 3',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '30%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 4',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '34.4%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 5',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '38.4%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 6',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '42.5%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 7',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '46.4%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 8',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '50.6%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
            {
                id: 'Bar Spot 9',
                isReserved: false,
                reservationDate: null,
                reservationHour: null,
                smokingStatus: 'Non-smokers',
                countOfPeople: '1',
                zone: 'Saloon',
                positionTop: '28.1%',
                positionLeft: '55%',
                rotation: '270deg',
                numberRotation: '90deg',
                numberPaddingRight: null,
            },
        ],
        selectedTableOrBarSpot: {},
        test: {},
    },
    reducers: {
        makeReservation: (state, action) => {
            const tableIndex = state.tables.findIndex(
                ({ id }) => id === action.payload,
            );
            if (tableIndex > -1) {
                state.selectedTableOrBarSpot = { ...state.tables[tableIndex] };
            }
        },
        makeReservationBarSpot: (state, action) => {
            const barSpotIndex = state.barSpots.findIndex(
                ({ id }) => id === action.payload,
            );
            if (barSpotIndex > -1) {
                state.selectedTableOrBarSpot = {
                    ...state.barSpots[barSpotIndex],
                };
            }
        },

        addNewReservation(state, action) {
            const targetIndex = state.tables.findIndex(
                (table) => table.id === action.payload.id,
            );
            if (targetIndex > -1) {
                state.tables[targetIndex] = action.payload.updatedObject;
            } else {
                const barSpotIndex = state.barSpots.findIndex(
                    (barSpot) => barSpot.id === action.payload.id,
                );

                state.barSpots[barSpotIndex] = action.payload.updatedObject;
            }
        },

        updateReservationStatus(state, action) {
            const targetIndex = state.tables.findIndex(
                (table) => table.id === action.payload.id,
            );
            const barSpotIndex = state.barSpots.findIndex(
                (barSpot) => barSpot.id === action.payload.id,
            );
            if (targetIndex > -1) {
                state.tables[targetIndex].isReserved =
                    action.payload.isReserved;
            }
            if (barSpotIndex > -1) {
                state.barSpots[barSpotIndex].isReserved =
                    action.payload.isReserved;
            }
        },
    },
});

export const tablesActions = tablesSlice.actions;
export default tablesSlice;
